services:
  backend:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
    command: sleep infinity
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    depends_on:
      - db
      - redis
  worker:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
    command: sleep infinity
    environment:
      - REDIS_HOST=redis
      - MINIO_ENDPOINT=minio:9000
    depends_on:
      - redis
      - minio
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=playbacq
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_NOTIFY_WEBHOOK_ENABLE_1=on
      - MINIO_NOTIFY_WEBHOOK_ENDPOINT_1=http://backend:8080/webhooks/minio
      - MINIO_API_CORS_ALLOW_ORIGIN=http://localhost:4200
    ports:
      - "9000:9000" # API用
      - "9001:9001" # コンソール用
    volumes:
      - minio_data:/data
  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./docker/minio/init.sh:/init.sh
    entrypoint: /bin/sh -c "chmod +x /init.sh && /init.sh"
volumes:
  db_data:
  redis_data:
  minio_data:
