openapi: 3.1.0
info:
  title: playbacQ
  version: "0.0.1"
  description: "playbacQサーバーのAPIです。"
  contact:
    name: traP
    url: "https://trap.jp/"
  
servers:
  - url: "http://localhost:8080"
    description: local

paths:
  /api/videos:
    get:
      summary: "動画一覧の取得"
      operationId: getVideos
      parameters:
        - schema:
            type: "string"
          name: "userId"
          in: "query"
          description: "ユーザーIDで動画をフィルタリングします。"
        - schema:
            type: "string"
          name: "search"
          in: "query"
          description: "動画のタイトルや説明で検索します。"
        - schema:
            type: "string"
          name: "tag"
          in: "query"
          description: "動画のタグでフィルタリングします。"
        - schema:
            type: "string"
          name: "sortby"
          in: "query"
          description: "動画の並び順を指定します。"
        - schema:
            type: "integer"
          name: "order"
          in: "query"
          description: "動画の並び順を昇順(1)か降順(0)で指定します。"
      responses:
        '200':
          description: "動画の一覧を取得します。"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Video'
    post:
      summary: "動画の投稿"
      operationId: createVideo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: "動画のタイトル"
                description:
                  type: string
                  description: "動画の説明"
      responses:
        '201':
          description: "動画が作成されました。"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'

  /api/videos/{id}:
    get:
      summary: "動画の取得"
      operationId: getVideoById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "動画のID"
      responses:
        '200':
          description: "動画を返します。"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
        '403':
          description: "アクセスが拒否されました。"
        '404':
          description: "動画が見つかりませんでした。"
  /api/videos/{id}/comments:
    get:
      summary: "動画のコメントの取得"
      operationId: getCommentsByVideoId
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "動画のID"
      responses:
        '200':
          description: "動画のコメントを返します。"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: array
                  items:
                    $ref: '#/components/schemas/Comment'
    post:
      summary: "動画のコメントの投稿"
      operationId: createComment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "動画のID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: "コメントの内容"
                timestamp:
                  type: number
                  format: double
                  description: "コメントの投稿時間"
      responses:
        '201':
          description: "コメントが作成されました。"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
  /api/videos/{id}/progress:
    get:
      summary: "動画のアップロードの進捗の取得"
      operationId: getVideoProgress
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "動画のID"
      responses:
        '200':
          description: "動画のアップロードの進捗を返します。"
          content:
            application/json:
              schema:
                type: object
                properties:
                  progress:
                    type: number
                    format: int
                    description: "動画のアップロードの進捗(0~100)"
                  status:
                    type: string
                    description: "動画のアップロードの状態(pending, processing, completed, failed)"
        '403':
          description: "アクセスが拒否されました。"
        '404':
          description: "動画が見つかりませんでした。"
  /api/videos/{id}/play:
    get:
      summary: "署名付きurlを含む.m3u8ファイルの取得"
      operationId: getVideoPlayUrl
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "動画のID"
      responses:
        '200':
          description: "署名付きurlを含む.m3u8ファイルを返します。"
          content:
            application/vnd.apple.mpegurl:
              schema:
                type: string
                description: "署名付きurlを含む.m3u8ファイルの内容"
        '403':
          description: "アクセスが拒否されました。"
        '404':
          description: "動画が見つかりませんでした。"
  /api/videos/{id}/views:
    post:
      summary: "動画の再生回数のインクリメント"
      operationId: incrementVideoViewCount
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "動画のID"
      responses:
        '200':
          description: "動画の再生回数がインクリメントされました。"
        '403':
          description: "アクセスが拒否されました。"
        '404':
          description: "動画が見つかりませんでした。"
  /api/videos/{id}/thumbnails/{thumbnailId}:
    get:
      summary: "サムネイル画像へリダイレクト"
      operationId: getVideoThumbnailUrl
      description: "サムネイル画像のURLを返すのではなく、直接サムネイル画像へリダイレクトします。これはWebTTファイル内でのみ使用します。"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "動画のID"
        - name: thumbnailId
          in: path
          required: true
          schema:
            type: string
          description: "サムネイルのID"
      responses:
        '200':
          description: "署名付きurlを含むサムネイル画像のURLを返します。"
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    description: "署名付きurlを含むサムネイル画像のURL"
        '403':
          description: "アクセスが拒否されました。"
        '404':
          description: "動画またはサムネイルが見つかりませんでした。"
  /api/videos/{id}/vtt:
    get:
      summary: "動画のサムネイルのWebVTTファイルの取得"
      operationId: getVideoThumbnailsVtt
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: "動画のID"
      responses:
        '200':
          description: "動画のサムネイルのWebVTTファイルを返します。"
          content:
            text/vtt:
              schema:
                type: string
                description: "動画のサムネイルのWebVTTファイルの内容"
        '403':
          description: "アクセスが拒否されました。"
        '404':
          description: "動画が見つかりませんでした。"
  /webhooks/minio:
    post:
      summary: "動画アップロードの通知用"
      operationId: minioWebhook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
  /webhooks/encode_result:
    post:
      summary: "動画エンコードの完了通知用"
      operationId: encodeResultWebhook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                videoId:
                  type: string
                  description: "動画のID"
                status:
                  type: string
                  description: "エンコードの状態(completed, failed)"
                message:
                  type: string
                  description: "success or error message"
                duration:
                  type: number
                  description: "動画の長さ(秒)"

components:
  schemas:
    Video:
      type: object
      properties:
        created_at:
          type: string
          format: date-time
          readOnly: true
          description: "動画の作成日時"
        id:
          type: string
          readOnly: true
          description: "動画のID"
        title:
          type: string
          readOnly: true
          description: "動画のタイトル"
        description:
          type: string
          readOnly: true
          description: "動画の説明"
        url:
          type: string
          readOnly: true
          description: "動画の公開用URL"
        thumbnailUrl:
          type: string
          readOnly: true
          description: "動画の公開用サムネイルURL"
        upload_url:
          type: string
          readOnly: true
          description: "動画のアップロード用URL"
        upload_thumbnail_url:
          type: string
          readOnly: true
          description: "動画のサムネイルアップロード用URL"
        viewCount:
          type: integer
          readOnly: true
          description: "動画の再生回数"
    Comment:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
          description: "コメントのID"
        content:
          type: string
          description: "コメントの内容"
        timestamp:
          type: number
          format: double
          description: "コメントの投稿時間"
        userId:
          type: string
          readOnly: true
          description: "コメントを投稿したユーザーのID"
        createdAt:
          type: string
          format: date-time
          readOnly: true
          description: "コメントの作成日時"