/**
 *
 *  VideoTags.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "VideoTags.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::playbacq;

const std::string VideoTags::Cols::_video_id = "video_id";
const std::string VideoTags::Cols::_tag_id = "tag_id";
const std::vector<std::string> VideoTags::primaryKeyName = {"video_id","tag_id"};
const bool VideoTags::hasPrimaryKey = true;
const std::string VideoTags::tableName = "video_tags";

const std::vector<typename VideoTags::MetaData> VideoTags::metaData_={
{"video_id","std::string","varchar(255)",255,0,1,1},
{"tag_id","int32_t","int",4,0,1,1}
};
const std::string &VideoTags::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
VideoTags::VideoTags(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["video_id"].isNull())
        {
            videoId_=std::make_shared<std::string>(r["video_id"].as<std::string>());
        }
        if(!r["tag_id"].isNull())
        {
            tagId_=std::make_shared<int32_t>(r["tag_id"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            videoId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            tagId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

VideoTags::VideoTags(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            videoId_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            tagId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

VideoTags::VideoTags(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("video_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["video_id"].isNull())
        {
            videoId_=std::make_shared<std::string>(pJson["video_id"].asString());
        }
    }
    if(pJson.isMember("tag_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["tag_id"].isNull())
        {
            tagId_=std::make_shared<int32_t>((int32_t)pJson["tag_id"].asInt64());
        }
    }
}

void VideoTags::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            videoId_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            tagId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

void VideoTags::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("video_id"))
    {
        if(!pJson["video_id"].isNull())
        {
            videoId_=std::make_shared<std::string>(pJson["video_id"].asString());
        }
    }
    if(pJson.isMember("tag_id"))
    {
        if(!pJson["tag_id"].isNull())
        {
            tagId_=std::make_shared<int32_t>((int32_t)pJson["tag_id"].asInt64());
        }
    }
}

const std::string &VideoTags::getValueOfVideoId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(videoId_)
        return *videoId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &VideoTags::getVideoId() const noexcept
{
    return videoId_;
}
void VideoTags::setVideoId(const std::string &pVideoId) noexcept
{
    videoId_ = std::make_shared<std::string>(pVideoId);
    dirtyFlag_[0] = true;
}
void VideoTags::setVideoId(std::string &&pVideoId) noexcept
{
    videoId_ = std::make_shared<std::string>(std::move(pVideoId));
    dirtyFlag_[0] = true;
}

const int32_t &VideoTags::getValueOfTagId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(tagId_)
        return *tagId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &VideoTags::getTagId() const noexcept
{
    return tagId_;
}
void VideoTags::setTagId(const int32_t &pTagId) noexcept
{
    tagId_ = std::make_shared<int32_t>(pTagId);
    dirtyFlag_[1] = true;
}

void VideoTags::updateId(const uint64_t id)
{
}
typename VideoTags::PrimaryKeyType VideoTags::getPrimaryKey() const
{
    return std::make_tuple(*videoId_,*tagId_);
}

const std::vector<std::string> &VideoTags::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "video_id",
        "tag_id"
    };
    return inCols;
}

void VideoTags::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getVideoId())
        {
            binder << getValueOfVideoId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTagId())
        {
            binder << getValueOfTagId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> VideoTags::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void VideoTags::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getVideoId())
        {
            binder << getValueOfVideoId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTagId())
        {
            binder << getValueOfTagId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value VideoTags::toJson() const
{
    Json::Value ret;
    if(getVideoId())
    {
        ret["video_id"]=getValueOfVideoId();
    }
    else
    {
        ret["video_id"]=Json::Value();
    }
    if(getTagId())
    {
        ret["tag_id"]=getValueOfTagId();
    }
    else
    {
        ret["tag_id"]=Json::Value();
    }
    return ret;
}

std::string VideoTags::toString() const
{
    return toJson().toStyledString();
}

Json::Value VideoTags::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getVideoId())
            {
                ret[pMasqueradingVector[0]]=getValueOfVideoId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTagId())
            {
                ret[pMasqueradingVector[1]]=getValueOfTagId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getVideoId())
    {
        ret["video_id"]=getValueOfVideoId();
    }
    else
    {
        ret["video_id"]=Json::Value();
    }
    if(getTagId())
    {
        ret["tag_id"]=getValueOfTagId();
    }
    else
    {
        ret["tag_id"]=Json::Value();
    }
    return ret;
}

bool VideoTags::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("video_id"))
    {
        if(!validJsonOfField(0, "video_id", pJson["video_id"], err, true))
            return false;
    }
    else
    {
        err="The video_id column cannot be null";
        return false;
    }
    if(pJson.isMember("tag_id"))
    {
        if(!validJsonOfField(1, "tag_id", pJson["tag_id"], err, true))
            return false;
    }
    else
    {
        err="The tag_id column cannot be null";
        return false;
    }
    return true;
}
bool VideoTags::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool VideoTags::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("video_id"))
    {
        if(!validJsonOfField(0, "video_id", pJson["video_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("tag_id"))
    {
        if(!validJsonOfField(1, "tag_id", pJson["tag_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    return true;
}
bool VideoTags::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool VideoTags::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
